version: '2'
services:
  db:
    image: postgres:9.5
    container_name: contact_list_db
    networks:
      - contact-list
    environment:
      - POSTGRES_USER=contact_list
      - POSTGRES_PASSWORD=contact_list
      - POSTGRES_DB=contact_list_test
    ports:
      - "5432:5432"
    networks:
      - contact-list

  web:
    image: caballerojavier13/contact_list_app:latest
    container_name: contact_list_app
    networks:
      - contact-list
    command: >
      bash -c "sleep 10 && 
               cd /contact-list &&  
               bundle exec rake db:migrate &&
               bin/rails server --port 3000 --binding 0.0.0.0"
    environment:
      - RAILS_ENV=test 
    ports:
      - "3000:3000"
    links:
      - "db:contact-list_db"
    networks:
      - contact-list
          
  test:
    image: caballerojavier13/contact_list_test:latest
    container_name: contact_list_test
    networks:
      - contact-list
  
  networks:
    - contact-list
